spring:
  jpa:
    hibernate:
      ddl-auto: update
      dynamic-insert: true
      dynamic-update: true
  datasource:
    url: jdbc:mysql://localhost:3306/hospitaldb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT
    username: root
    password: